# 这是部署时的配置文件，也是本地开发的入口
name = "my-photo-worker" # 你的 Worker 名字
main = "src/index.ts"
compatibility_date = "2024-05-02"

# 告诉 Cloudflare Pages 如何构建和集成这个项目
# 这是 Monorepo 部署的关键
[pages_build]
# 前端项目的目录
build_dir = "../frontend"
# 前端项目的构建命令
build_command = "npm install && npm run build"
# 构建产物的输出目录
build_output_dir = "dist"

# 绑定 R2 存储桶，让 Worker 可以访问
[[r2_buckets]]
binding = "PHOTO_BUCKET" # 代码中通过 env.PHOTO_BUCKET 访问
bucket_name = "your-r2-bucket-name" # 【重要】替换成你创建的 R2 存储桶的真实名称

# 绑定环境变量，在部署后需要在 Cloudflare 仪表盘设置
[vars]
ALLOWED_ORIGINS = "https://your-pages-project.pages.dev" # 【重要】部署后替换成你的 Pages 域名

# 注意：密钥(Secrets)不能写在这里，需要通过命令行或仪表盘设置
# R2_ACCOUNT_ID
# R2_ACCESS_KEY_ID
# R2_SECRET_ACCESS_KEY

